name: easy_attribution_text
description: "Easily add metadata attributes to your text and modify your fragments"
version: 1.0.2
homepage: https://github.com/CatHood0/easy_rich_editor/tree/Main/easy_text
documentation: https://github.com/CatHood0/easy_rich_editor/tree
issue_tracker: https://github.com/CatHood0/easy_rich_editor/tree/Main/easy_text

environment:
  sdk: '>=3.4.3 < 4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  collection: ^1.18.0
  uuid: ^4.5.1
  characters: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
